# Generated by Django 5.2 on 2025-04-22 18:59

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("species", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="co2_tolerance",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="common_names",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2025, 4, 22, 19, 58, 39, 832521),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="species",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="edibility",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="is_cubes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="species",
            name="light_requirements",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="medicinal_properties",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="optimal_humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="optimal_temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="photo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="scientific_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="species",
            name="substrate_preferences",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="taxonomy_family",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="taxonomy_genus",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="taxonomy_order",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="species",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
