# Generated by Django 5.2 on 2025-04-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("species", "0002_species_co2_tolerance_species_common_names_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="is_custom",
            field=models.BooleanField(default=False),
        ),
    ]
